<?php

if (!defined('WHMCS')) {
    die('No direct access');
}

if (!function_exists('peakrackRiskAdminLanguage')) {
    function peakrackRiskAdminLanguage(array $settings): string
    {
        $language = (string) ($settings['adminLanguage'] ?? 'en');
        return in_array($language, ['en', 'zh'], true) ? $language : 'en';
    }
}

if (!function_exists('peakrackRiskAdminText')) {
    function peakrackRiskAdminText(string $language, string $key): string
    {
        $texts = [
            'en' => [
                'saved' => 'Settings saved successfully.',
                'token_failed' => 'Security token validation failed. Please reload the page and try again.',
                'page_title' => 'Risk Control Center',
                'subtitle' => 'Manage order review rules, checkout notice copy, and audit records.',
                'save' => 'Save Settings',
                'enabled' => 'Enabled',
                'disabled' => 'Disabled',
                'mode' => 'Mode',
                'manual_review' => 'Manual review',
                'log_only' => 'Log only',
                'auto_fraud_enabled' => 'Auto fraud enabled',
                'review_threshold' => 'Review Threshold',
                'fraud_threshold' => 'Fraud Threshold',
                'checkout' => 'Checkout',
                'notice_enabled' => 'Notice enabled',
                'notice_disabled' => 'Notice disabled',
                'general_controls' => 'General Controls',
                'general_desc' => 'Enable runtime behavior. Automatic fraud marking is intentionally separate from high-score review.',
                'enable_risk_engine' => 'Enable risk engine',
                'enable_checkout_notice' => 'Enable checkout notice',
                'require_server_ack' => 'Require server acknowledgement',
                'allow_auto_fraud' => 'Allow automatic FraudOrder',
                'admin_language' => 'Admin language',
                'english' => 'English',
                'chinese' => 'Chinese',
                'thresholds' => 'Thresholds',
                'thresholds_desc' => 'Scores are normalized to 0-100. Orders at or above review threshold are moved to Pending.',
                'review_help' => 'Move order to Pending when score reaches this value.',
                'fraud_help' => 'High-risk cutoff. FraudOrder only runs when auto fraud is enabled.',
                'api_retries' => 'API retries',
                'api_help' => 'Retries for PendingOrder and FraudOrder localAPI calls.',
                'ip_burst_window' => 'IP burst window',
                'ip_burst_window_help' => 'Lookback window in minutes for repeated orders from one IP.',
                'ip_burst_count' => 'IP burst count',
                'ip_burst_count_help' => 'Number of orders from the same IP that triggers burst risk.',
                'lists' => 'Lists',
                'lists_desc' => 'Use one item per line. Country codes should be ISO two-letter values.',
                'high_risk_countries' => 'High risk countries',
                'trusted_email_domains' => 'Trusted email domains',
                'whitelist_client_ids' => 'Whitelist client IDs',
                'whitelist_group_ids' => 'Whitelist client group IDs',
                'whitelist_email_domains' => 'Whitelist email domains',
                'whitelist_ip_cidrs' => 'Whitelist IP/CIDR',
                'one_per_line' => 'One item per line or comma separated.',
                'risk_weights' => 'Risk Weights',
                'weights_desc' => 'Positive values add risk. Negative values reduce risk for trusted signals.',
                'checkout_text' => 'Checkout Text',
                'checkout_text_desc' => 'These fields control the acknowledgement dialog shown on the cart checkout page.',
                'checkout_items_help' => 'One bullet per line. These lines are shown in the checkout notice.',
                'recent_decisions' => 'Recent Decisions',
                'recent_decisions_desc' => 'Latest order-level risk actions persisted by the addon.',
                'recent_logs' => 'Recent Audit Logs',
                'recent_logs_desc' => 'Operational log entries mirrored to WHMCS activity logs.',
                'no_decisions' => 'No decisions recorded yet.',
                'no_logs' => 'No audit logs recorded yet.',
                'order' => 'Order',
                'client' => 'Client',
                'score' => 'Score',
                'action' => 'Action',
                'processed' => 'Processed',
                'time' => 'Time',
                'level' => 'Level',
                'message' => 'Message',
            ],
            'zh' => [
                'saved' => '设置已保存。',
                'token_failed' => '安全令牌验证失败，请刷新页面后重试。',
                'page_title' => '风控管理中心',
                'subtitle' => '管理订单审核策略、结账确认文案与审计记录。',
                'save' => '保存设置',
                'enabled' => '已启用',
                'disabled' => '已禁用',
                'mode' => '运行模式',
                'manual_review' => '人工审核',
                'log_only' => '仅记录日志',
                'auto_fraud_enabled' => '自动标记欺诈已启用',
                'review_threshold' => '审核阈值',
                'fraud_threshold' => '欺诈阈值',
                'checkout' => '结账提醒',
                'notice_enabled' => '提醒已启用',
                'notice_disabled' => '提醒已禁用',
                'general_controls' => '基础控制',
                'general_desc' => '控制插件运行行为。自动标记欺诈与高风险审核分开控制。',
                'enable_risk_engine' => '启用风控引擎',
                'enable_checkout_notice' => '启用结账提醒',
                'require_server_ack' => '要求服务端确认',
                'allow_auto_fraud' => '允许自动执行 FraudOrder',
                'admin_language' => '后台语言',
                'english' => 'English',
                'chinese' => '中文',
                'thresholds' => '阈值设置',
                'thresholds_desc' => '评分会归一化到 0-100。达到审核阈值的订单会进入 Pending。',
                'review_help' => '订单评分达到该值时转为 Pending。',
                'fraud_help' => '高风险分界值。只有启用自动欺诈时才执行 FraudOrder。',
                'api_retries' => 'API 重试次数',
                'api_help' => 'PendingOrder 和 FraudOrder 本地 API 调用的重试次数。',
                'ip_burst_window' => 'IP 爆发窗口',
                'ip_burst_window_help' => '检测同一 IP 重复下单的回看分钟数。',
                'ip_burst_count' => 'IP 爆发订单数',
                'ip_burst_count_help' => '同一 IP 达到该订单数后触发爆发风险。',
                'lists' => '名单配置',
                'lists_desc' => '每行一个值。国家代码建议使用 ISO 两位代码。',
                'high_risk_countries' => '高风险国家',
                'trusted_email_domains' => '可信邮箱域名',
                'whitelist_client_ids' => '白名单客户 ID',
                'whitelist_group_ids' => '白名单客户组 ID',
                'whitelist_email_domains' => '白名单邮箱域名',
                'whitelist_ip_cidrs' => '白名单 IP/CIDR',
                'one_per_line' => '每行一个，也可用英文逗号分隔。',
                'risk_weights' => '风险权重',
                'weights_desc' => '正数增加风险，负数降低可信信号的风险。',
                'checkout_text' => '结账文案',
                'checkout_text_desc' => '这些字段控制购物车结账页弹窗显示内容。',
                'checkout_items_help' => '每行一条，将作为结账提醒中的列表项显示。',
                'recent_decisions' => '最近决策',
                'recent_decisions_desc' => '插件保存的最新订单风险处理结果。',
                'recent_logs' => '最近审计日志',
                'recent_logs_desc' => '同时写入 WHMCS 活动日志的运行记录。',
                'no_decisions' => '暂无决策记录。',
                'no_logs' => '暂无审计日志。',
                'order' => '订单',
                'client' => '客户',
                'score' => '评分',
                'action' => '动作',
                'processed' => '处理时间',
                'time' => '时间',
                'level' => '级别',
                'message' => '消息',
            ],
        ];

        $language = in_array($language, ['en', 'zh'], true) ? $language : 'en';
        return $texts[$language][$key] ?? $texts['en'][$key] ?? $key;
    }
}
